{{- if not .Values.gate.auth.existingSecret }}
{{- if or (eq .Values.gate.auth.type "token") (eq .Values.gate.auth.type "basic") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spinnaker-mcp.fullname" . }}
  labels:
    {{- include "spinnaker-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq .Values.gate.auth.type "token" }}
  GATE_TOKEN: {{ .Values.gate.auth.token | quote }}
  {{- end }}
  {{- if eq .Values.gate.auth.type "basic" }}
  GATE_USER: {{ .Values.gate.auth.user | quote }}
  GATE_PASS: {{ .Values.gate.auth.pass | quote }}
  {{- end }}
{{- end }}
{{- end }}
